### ISSUE TITLE
Slide Suggestions

### ISSUE THREAD

**Issue by steiltre** [LLNL/metall#123]
Just read through the (excellent!) slides in the NVMW tutorial branch. Here are a few small suggestions to make them read more naturally.

Slide 2:
-"one of key challenges" -> "one of the key challenges" or "a key challenge"
-"multiple analytics to the same data" -> "multiple analytics on the same data"

Slide 4:
-"dismantling and assembling large complex data structures are" -> "dismantling and assembling large complex data structures is"
-"transparent accesses to applications" -> "transparent access to applications"

Slide 8:
-"destructor synchronies" -> "destructor synchronizes"

Slide 11:
-"object is points" -> "object is points to"

Slide 13:
-"improve I/O performance" -> "improves I/O performance"

Slide 17:
-"clash" -> "crash"

Slide 18:
-"Snapshot/versioning" -> "Snapshot/Versioning" (capitalization)

Slide 23:
-Maybe make the highlighted text red to emphasize that those points are negative

**Comment by KIwabuchi** [comment]
Again, I really appreciate your suggestions!  I made changes to the slides (5f8aa5fc47b6ef57b5a5bc8f032d3ddeec4f2732).
