### ISSUE TITLE
Set default boost version to boost-1.77.0 

### ISSUE THREAD

**Issue by kaushikvelusamy** [LLNL/metall#170]
Minor Issue: 

Spack picks up the default boost dependency version from here. 
Setting default boost version to boost-1.77.0 avoids all pragma deprecation warnings and gives a clean compilation. 
update needed at metall.readthedocs.io, readme, and gitlab-ci.yml.

**Comment by KIwabuchi** [comment]
Thanks for the information, Kaushik!
Metall Spack package is designed to install the latest boost version available in Spack.
Let's hope Spack supports boost-1.77.0 soon...
Once boost-1.77.0 is available in Spack, I'll update the documents and CI configurations.

**Comment by KIwabuchi** [comment]
Spack supports Boost 1.77.0. I updated the documents and CI configurations.
