### ISSUE TITLE
How to do performance tuning?

### ISSUE THREAD

**Issue by bigerl** [LLNL/metall#204]
Hi and first of all thx for this great piece of software. 

We have just implemented persistence for our RDF graph store [tentris](https://tentris.dice-research.org/) (still in a private repo, though) at the [DICE](https://github.com/dice-group) research group. It seems to scale well up to 8 million edges. After that insertion performance decreases significantly (factor 10+). With `std::allocator`, so without any persistence, it scales well up to several billion edges.

So I have some questions regarding performance tuning. 😄 

First: You wrote in the metall overview slides on slide 21 that you did:

> mmap (VM tuned)
> • system mmap + Metall
> • Tuned page cache behaviors
> • Required privileged access
> • System-wide change

Could you share those settings? The difference in the plot seems significant. 
![image](https://user-images.githubusercontent.com/933146/151139662-2d73e395-1cb9-46e8-88b1-793e4dcb69cc.png)

Second: The umap backend in the above plot looks most promising. But you mention [here in the docs](https://github.com/LLNL/metall/blob/fb02ff15bc9f5a00e0583bf76c9e097464f037f6/docs/readthedocs/advanced_build/umap.md) that the umap back end does not give any memory back. Neither DRAM nor storage in the backing file. Is this still up-to-date? 
Would it need work in metall or umap or both to address these issues?

And Third: What are the largest memory footprints in GB you handled with metall so far?

**Comment by KIwabuchi** [comment]
Hi @bigerl,

It's great to hear that Metall is working with your team's software, tentris😃

**1. VM tuning**

We used the following commands to change VM's behaviors. By default, Linux kernel starts writing back dirty pages when some amount of pages are dirty (e.g., 20% of DRAM capacity). So, we increased the threshold value to delay the write back.

```bash
sudo sh -c "echo 90 > /proc/sys/vm/dirty_ratio"
sudo sh -c "echo 80 > /proc/sys/vm/dirty_background_ratio"
sudo sh -c "echo 300000000 > /proc/sys/vm/dirty_expire_centisecs"
```

If your application does't have to allocate data larger than DRAM capacity, you can also create Metall datastores on 'tmps' (e.g., /dev/shm). tmps is a filesystem built on top of DRAM space. So, you can achieve high I/O performance. Please note that all files on tmpfs will be lost when the machine is shut down. So, you need to copy Metall datastore to another location if you want to keep the data. I'm happy to tell you more detail if you are interested in:)


**2. Umap** 

Yes, it is still up-to-date. Umap cannot free memory space for now.
Please note that there are some Linux kernel requirements to use Umap:
https://github.com/LLNL/umap#build-requirements

**3. Largest memory footprints**

I would say that was a few TB. 

**4. PR**
BTW, I left a comment to your PR. I don't have any objection to your PR. I just wanted to understand the intentions of your changes:)

**Comment by bigerl** [comment]
thx for the detailed response. @KIwabuchi 

**@1. VM tuning**

that improved the performance already a lot

**@2. Umap**

yes, we would definitely need it as the knowledge graphs we store can both grow and shrink. Resources should be released when not needed anymore to be available for other tasks. Please let me know, if we can be of any assistance here. 

Regarding kernel features: Linux 5.10+ works for us as a requirement. 

**@3. Largest memory footprints**

That sounds great!

**@4. PR**

I could find your comment but I'll just add an explanation.

**Comment by mayagokhale** [comment]
Re point 2. We discussed having the application (Metall) free memory (and therefore storage blocks) and think it is implementable without having to add to the UMap API. We are looking into adding this feature to UMap.

**Comment by KIwabuchi** [comment]
Hi @bigerl 

**VM Tuning**

That's great!

**PR**

I've already merged your PR and published a new version that contains your PR. Again, thanks for the PR!

Please feel free to ask us if you have any further questions.

**Comment by bigerl** [comment]
thx for the help. I am looking forward to the option of freeing memory with metall+umap. Just let me if I can be of any help there. 

I'll close this issue now.
