### ISSUE TITLE
Datastore is "inconsistent" when the program ends, while the snapshot appears to be working for "complex map"

### ISSUE THREAD

**Issue by illegalplumbing** [LLNL/metall#254]
When a "complex map" is created and populated with data, the data store on the disk appears to be "incomplete" with the following error message:

include/metall/kernel/manager_kernel_impl.ipp at line 941 --- Inconsistent data store — it was not closed properly and might have been collapsed.

If the snapshot is created, it is working properly
This does not happen for "simpler" value types

Ubuntu 22.04.1 LTS
boost 1.74
g++ 17

I attached the code which produces the error

[main.cc.zip](https://github.com/LLNL/metall/files/9964376/main.cc.zip)

**Comment by KIwabuchi** [comment]
I'm closing this since there has been no update, and Metall did not cause the issue, apparently.
