### ISSUE TITLE
Suggestion: Make fallback_allocator::stateful_allocatorator_available() public

### ISSUE THREAD

**Issue by bigerl** [LLNL/metall#326]
https://github.com/LLNL/metall/blob/1f6c027680ea89bf92bd9a5255e006c044aa078f/include/metall/container/fallback_allocator.hpp#L217-L219

We use the fallback_allocator in an algorithm that behaves differently based on weather the stateful allocator is used or not. ATM, we just re-implement the `private_stateful_allocatorator_available()` in our code. 

I would suggest to make a public `stateful_allocatorator_available()`. Shouldn't hurt because the interfaces to calculate the result are public anyway and might come in handy for others. 

PS: Is allocator**ator** a pun or a typo?

**Comment by KIwabuchi** [comment]
That's a good idea. I'll implement a public function`stateful_allocatorator_available()` .

Oh, allocatorator is a type. I'll also fix that.

**Comment by KIwabuchi** [comment]
BTW, would you like to set up a web meeting to discuss Metall sometime this Month?
I'm happy to take questions and/or new feature requests.
