### ISSUE TITLE
difference between the 2 umap storages

### ISSUE THREAD

**Issue by bigerl** [LLNL/metall#330]
I was just looking for the umap segment storage and found two of them:
- [umap_sparse_segment_storage.hpp](https://github.com/LLNL/metall/blob/1f6c027680ea89bf92bd9a5255e006c044aa078f/include/metall/kernel/segment_storage/umap_sparse_segment_storage.hpp)
- [umap.hpp](https://github.com/LLNL/metall/blob/1f6c027680ea89bf92bd9a5255e006c044aa078f/include/metall/ext/umap.hpp)

What is the difference?

**Comment by bigerl** [comment]
alright, thank you.

**Comment by KIwabuchi** [comment]
I'll try to make more detailed documentation about using Umap with Metall.
