### ISSUE TITLE
using typedef produces a compilation error in clang

### ISSUE THREAD

**Issue by correaa** [LLNL/metall#49]
This simple program doesn't compile with clang because of a redefiniton

```c++
// clang++ -std=c++17 -I$HOME/github.com/LLNL/metall.git/include/ main.cpp
#include<metall/metall.hpp>

int main(){}
```

commenting this line (15) in `metall.hpp` seems to work:

```c++
template <typename chunk_no_type, std::size_t chunk_size, typename kernel_allocator_type>
using basic_manager = basic_manager<chunk_no_type, chunk_size, kernel_allocator_type>;
```

this line doesn't seem to add information anyway because it repeats all the types. 

I know the library explicitly requires clang, but it probably does for different reasons.

**Comment by KIwabuchi** [comment]
Thank you for sending us the issue. That line is a bug. I'll fix it today.

The line used to be like this:
`
template <typename chunk_no_type, std::size_t chunk_size, typename kernel_allocator_type>
using basic_manager = v0::basic_manager<chunk_no_type, chunk_size, kernel_allocator_type>
`
I recently removed 'v0' namespace, and the line became invalid.

**Comment by KIwabuchi** [comment]
Thanks for the PR! I'm closing this issue.
