### ISSUE TITLE
cuda compiler complains about defaulted copy assignment

### ISSUE THREAD

**Issue by correaa** [LLNL/metall#61]
with a miminal example:

```
clang++ -x cuda -Wall -Wextra -Ofast -Wfatal-errors -Wpedantic -Wmove -std=c++17 --cuda-gpu-arch=sm_60 
In file included from ./llnl_metall.cpp:10:
In file included from github.com/LLNL/metall.git/include/metall/metall.hpp:9:
In file included from /github.com/LLNL/metall.git/include/metall/basic_manager.hpp:16:
In file included from /github.com/LLNL/metall.git/include/metall/kernel/manager_kernel.hpp:21:
In file included from /github.com/LLNL/metall.git/include/metall/kernel/segment_allocator.hpp:18:
/github.com/LLNL/metall.git/include/metall/kernel/bin_directory.hpp:85:18: fatal error: the parameter for this explicitly-defaulted copy assignment operator is const, but a member or base requires it to be non-const
  bin_directory &operator=(const bin_directory &) = default;
```

I don't know if the member is `table_type` (aka `boost::container::vector`), it would be strange that it doesn't have an `operator=(T const&){...}`.

**Comment by KIwabuchi** [comment]
Hmm, that's a strange error. I'll look into it!

**Comment by correaa** [comment]
yes, maybe something specific of the front end. I think different compilers interpret `= default` differently, for example if it was deleted by a base class, they complain that they can't be defaulted and must be deleted. I think, it is a bad interpretation, in the sense that default might mean delete depending on the context.

**Comment by KIwabuchi** [comment]
Are you using a LC cluster or your own machine? I'm trying to setup a clang + CUDA environment. Also which Boost version did you use?

**Comment by correaa** [comment]
Own machine. 

```bash
$ clang++ --version
clang version 9.0.0-2 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ grep LIB_VERSION /usr/include/boost/version.hpp 
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_67"

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
```

**Comment by KIwabuchi** [comment]
Thank you for your quick response!

**Comment by KIwabuchi** [comment]
I think I found something. Apparently, the error does not happen with Boost libraries equal to or more than v1.69. Could you try with one of the versions?

**Comment by correaa** [comment]
Yes, I coincidentally upgrade to 1.71 and it works.

Maybe a workaround for old versions of Boost and clang+cuda is to actually define the body of `operator=`. Not sure if its worth.

**Comment by KIwabuchi** [comment]
Great! Sorry for taking too long to find out. I struggled with setting up the clang + cuda environment... Thank you for trying Metall with CUDA.

Right, as Boost containers are everywhere in Metall, making a workaround could be costly.
As Metall does not require a build for Boost, I hope preparing relatively newer Boost versions wouldn't be a big deal for users.
For now, I'll write a memo about this problem in the documents.

**Comment by KIwabuchi** [comment]
Add a memo about the problem into documents ( see #65 ) . Closing this issue.
